version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_DB_PATH=/data
      - POSTHOG_DISABLED=true
    volumes:
      - ./chromadb_data:/data
