version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - chromadb
    command: ["poetry", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--log-level", "debug"]

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_DB_PATH=/data
      - POSTHOG_DISABLED=true
    volumes:
      - ./chromadb_data:/data
